---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes
  tags: nginx.install

- name: check for original nginx.conf
  stat:
    path: /etc/nginx/orgin.nginx.conf
  register: origin_nginx
  tags: nginx.install

- name: backup original nginx.conf
  command: mv -n /etc/nginx/nginx.conf /etc/nginx/orgin.nginx.conf
  when: origin_nginx.stat.exists == false
  tags: nginx.install

- name: Copy in new nginx.conf
  copy:
    src: "roles/nginx/files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    remote_src: no
  tags: nginx.install

- name: create fcgi directory
  file:
    path: /usr/share/nginx/cache/fcgi
    state: directory
  tags: nginx.install

- name: Test new nginx.conf
  shell: nginx -t
  register: nConf_test
  failed_when: nConf_test.rc != 0
  notify: restart nginx
  tags: nginx.statusCheck

- name: remove 'Welcome to Nginx' file
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
  tags: nginx.remove-index








